#!/usr/bin/env ruby
# frozen_string_literal: true
# encoding: UTF-8
# warn_indent: true

require 'daemons/rails'
script_path = File.expand_path(__FILE__)
config = ::Daemons::Rails::Config.for_controller(script_path)
Daemons::Rails.run(script_path, ARGV.dup, config)
